# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  django:shell:
    cmds:
      - poetry run python manage.py shell

  django:run:
    cmds:
      - poetry run python manage.py runserver